

name: for_push_and_pr


on:

  push:
  
    branches: [ main ]
  pull_request:
    branches: [ main ]


 

jobs:

  build:

    runs-on: ${{matrix.os}}
   
    strategy:
      matrix:
        os: [mac-latest, window-latest, ubuntu]

    steps:
      - uses: actions/checkout@v3

      
      - name: Run a one-line script
        run: echo Hello there,hope you're having a nice day!

